estimator:
  pickle: model.pickle

strategy:
  name: random

search_space:
  atomcenteredsymmetryfunctions__nbasis:
    min: 6
    max: 30
    type: int
    warp: log

  atomcenteredsymmetryfunctions__cutoff:
    min: 3
    max: 5
    type: float
    warp: log

  atomcenteredsymmetryfunctions__precision:
    min: 1.05
    max: 3
    type: float
    warp: log

  neuralnetwork__hl1:
    min: 30
    max: 500
    type: int
    warp: log

  neuralnetwork__hl2:
    min: 30
    max: 500
    type: int
    warp: log

  neuralnetwork__batch_size:
    min: 10
    max: 200
    type: int
    warp: log

  neuralnetwork__iterations:
    min: 300
    max: 5000
    type: int
    warp: log

  neuralnetwork__learning_rate:
    min: 4e-4
    max: 3e-3
    type: float
    warp: log

  neuralnetwork__l2_reg:
    min: 1e-8
    max: 4e-4
    type: float
    warp: log

  neuralnetwork__l1_reg:
    min: 1e-7
    max: 1e-2
    type: float
    warp: log

cv:
  name: KFold
  params:
    n_splits: 3

dataset_loader:
  name: dsv
  params:
    filenames: idx.csv

trials:
    uri: sqlite:///osprey-trials1.db
